### ISSUE TITLE
I can not find it on play store.

### ISSUE THREAD

**Issue by ingnelson** [AndyLeezard/CoinTracer_public#1]
Hello sir.

Could you give me the link where to download the app on play store , please ? 

From what exchange get the data ? This way I look for the right chart on tradingview .

**Comment by raeinlee** [comment]
Hello ingnelson,

Please find attached the URL requested.

Google Play URL: https://play.google.com/store/apps/details?id=com.AndyLeeDev.CoinTracer
AppStore URL: https://apps.apple.com/us/app/coin-tracer/id1579682178

Note that another update is currently in review on both sides (1.0.8 on Android and 1.0.7 on iOS which are identical), now supporting language preferences and redirection from a trading screen to CoinMarketCap too.

Also, CoinTracer is using synthetic real-time crypto prices data from more than 489 exchanges as of August 21, 2021, provided by Coingecko.com API. Their API is free for commercial use with the right attribution (mentioned in the Terms of Use of CoinTracer).
Therefore any major exchange (Coinbase, Binance, Huobi Global, FTX, Kraken, etc ...) available on Tradingview should be reliable as the right charts and indicators.

Thank you for using my app.

![image](https://user-images.githubusercontent.com/77301332/130352517-fc76a404-8380-4bd9-b946-c4f4fa739e5a.png)

**Comment by ingnelson** [comment]
@AndyLeezard hello. I just install the version 1.0.6 I just sign up , then crash . I tried to open it many times but , crashed .
Maybe the next version.

**Comment by raeinlee** [comment]
Hello @ingnelson,

The issue has been established and verified thanks to your feedback.
The 1.0.6 version seems particularly bugged for Android devices as I could not reproduce the same issue on iOS devices.
I apologize for the inconvenience.
This application is still fairly new and I strive to make it better.

I submitted a new version with a hotfix (1.0.9) for Android on Google Play, this can take a couple of days to be approved.

Meanwhile, I can provide you a tester account if you're interested.

Please wait for the update, thank you.

**Comment by raeinlee** [comment]
A little update: 1.0.9 is now available on Android and I'm glad to announce that the issue has been resolved.
I tested and confirmed it with my device.

Please try again to register, thank you.

**Comment by raeinlee** [comment]
The app has been unpublished and archived.
